#!/bin/sh

linux_get_bat ()
{
	bf=$(cat $BAT_FULL)
	bn=$(cat $BAT_NOW)
	echo $(( 100 * $bn / $bf ))
}

ac_status()
{
	output=$(acpi -a);
	if [[ $output == *off* ]]
	then
	  echo "↓";
	else
	  echo "";
	fi
}

battery_status()
{
	BATPATH=${BATPATH:-/sys/class/power_supply/BAT0}
	STATUS=$BATPATH/status
	[ "$1" = `cat $STATUS` ] || [ "$1" = "" ] || return 0
	if [ -f "$BATPATH/energy_full" ]; then
	    naming="energy"
	elif [ -f "$BATPATH/charge_full" ]; then
	    naming="charge"
	elif [ -f "$BATPATH/capacity" ]; then
	    cat "$BATPATH/capacity"
	    return 0
	fi
	BAT_FULL=$BATPATH/${naming}_full
	BAT_NOW=$BATPATH/${naming}_now
	linux_get_bat
}

BATTERY_STATUS=`battery_status $1`
[ -z "$BATTERY_STATUS" ] && exit

AC_STATUS=`ac_status $1`

echo "⚡${AC_STATUS} ${BATTERY_STATUS}%"
